spring:
  profiles: consumer
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
server:
  port: 9096

---

spring:
  profiles: producer
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
server:
  port: 9095
  servlet:
    context-path: /kotlin-test
