version: "3.1"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
  producer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PROFILE: producer
    ports:
      - 9095:9095
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq
  consumer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PROFILE: consumer
    ports:
      - 9096:9096
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq